title: Project Information
description: Een interactieve datavisualisatie over de criminaliteit tijdens de corona periode in Nederkand
url: https://itsguus.github.io/project_information/


defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
