title: Criminaliteit tijdens Covid-19
description: Een interactieve datavisualisatie over de criminaliteit tijdens de corona periode in Nederkand
url: 


defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
